name: Build & Test

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  build:
  runs-on: ubuntu-latest

  strategy: 
    matrix:
      node-version: [18.x]
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #db setup here: https://redwoodjs.com/docs/how-to/test-in-github-actions#4-set-up-GitHub-actions
 steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # install all the dependencies
      - run: yarn install
      # build the redwood app
      - run: yarn rw build
      # run the api tests
      - run: yarn rw test api --no-watch
      # run the web tests
      - run: yarn rw test web --no-watch